WebApplication1/Models/crsResult.cs
namespace WebApplication1.Models
{
    public class crsResult

    {
        public int Id { get; set; }
        public int Degree { get; set; }

        public int CourseId { get; set; }

        public int TraineeId { get; set; }

        public virtual Course Course { get; set; }


        public virtual Trainee Trainee { get; set; }




    }
}

WebApplication1/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CoursesController : Controller
    {
        private readonly Data.ApplicationDbContext _context;

        public CoursesController(Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Courses.Include(c => c.Department);
            return View(await applicationDbContext.ToListAsync());
        }


        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .Include(c => c.Department)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            ViewData["departmentId"] = new SelectList(_context.Set<Department>(), "Id", "Id");
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,degree,Mindegree,departmentId")] Course course)
        {

            // Check if course name is unique
            if (_context.Courses.Any(c => c.Name == course.Name))
            {
                ModelState.AddModelError("Name", "Course name already exists.");
                return View(course);
            }

            // If unique, add the course to the database
            _context.Add(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));



        }


        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            ViewData["departmentId"] = new SelectList(_context.Set<Department>(), "Id", "Id", course.departmentId);
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,degree,Mindegree,departmentId")] Course course)
        {
            if (id != course.Id)
            {
                return NotFound();
            }


            try
            {
                _context.Update(course);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CourseExists(course.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));

        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .Include(c => c.Department)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Courses.FindAsync(id);
            if (course != null)
            {
                _context.Courses.Remove(course);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.Courses.Any(e => e.Id == id);
        }

      

    }
}

WebApplication1/Controllers/TraineesController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using static System.Runtime.InteropServices.JavaScript.JSType;
using WebApplication1.Models;

public class TraineesController : Controller
{
    private readonly WebApplication1.Data.ApplicationDbContext _context;

    public TraineesController(WebApplication1.Data.ApplicationDbContext context)
    {
        _context = context;
    }
    private bool TraineeExists(int id)
    {
        return _context.Trainees.Any(e => e.Id == id);
    }

    // GET: Trainees
    public async Task<IActionResult> Index()
    {
        var applicationDbContext = _context.Trainees.Include(t => t.Department);
        return View(await applicationDbContext.ToListAsync());
    }

    // GET: Trainees/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var trainee = await _context.Trainees
            .Include(t => t.Department)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (trainee == null)
        {
            return NotFound();
        }

        return View(trainee);
    }

    // GET: Trainees/Create
    public IActionResult Create()
    {
        PopulateDepartmentsDropDownList();
        return View();
    }

    // POST: Trainees/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Name,Image,Address,Grade,DepartmentId")] Trainee trainee)
    {
        // Manual validation
        var errors = new List<string>();

        if (string.IsNullOrEmpty(trainee.Name))
        {
            errors.Add("Name is required.");
        }
        if (string.IsNullOrEmpty(trainee.Image))
        {
            errors.Add("Image URL or path is required.");
        }
        if (string.IsNullOrEmpty(trainee.Address))
        {
            errors.Add("Address is required.");
        }
        if (trainee.Grade <= 0)
        {
            errors.Add("Grade must be greater than zero.");
        }
        if (trainee.DepartmentId <= 0)
        {
            errors.Add("A valid department must be selected.");
        }

        if (errors.Any())
        {
            PopulateDepartmentsDropDownList(trainee.DepartmentId);
            ViewData["Errors"] = errors;
            return View(trainee);
        }

        try
        {
            _context.Add(trainee);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        catch (DbUpdateException ex)
        {
            ViewData["Errors"] = new List<string> { "Unable to save changes. Please try again." };
            PopulateDepartmentsDropDownList(trainee.DepartmentId);
            return View(trainee);
        }
    }
    // GET: Trainees/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var trainee = await _context.Trainees.FindAsync(id);
        if (trainee == null)
        {
            return NotFound();
        }

        // Populate drop-down lists
        ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name", trainee.DepartmentId);

        return View(trainee);
    }


    // POST: Trainees/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Image,Address,Grade,DepartmentId")] Trainee trainee)
    {
        if (id != trainee.Id)
        {
            return NotFound();
        }

        // Ensure the departmentId is valid
        var departmentExists = await _context.Departments.AnyAsync(d => d.Id == trainee.DepartmentId);
        if (!departmentExists)
        {
            ModelState.AddModelError("DepartmentId", "Selected department does not exist.");
        }

        if (ModelState.IsValid)
        {
            try
            {
                var existingTrainee = await _context.Trainees.FindAsync(id);
                if (existingTrainee == null)
                {
                    return NotFound();
                }

                _context.Entry(existingTrainee).CurrentValues.SetValues(trainee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TraineeExists(trainee.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
        }

        // Repopulate the drop-down list in case of validation failure
        ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name", trainee.DepartmentId);
        return View(trainee);
    }


    // GET: Trainees/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var trainee = await _context.Trainees
            .Include(t => t.Department)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (trainee == null)
        {
            return NotFound();
        }

        return View(trainee);
    }

    // POST: Trainees/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var trainee = await _context.Trainees.FindAsync(id);
        if (trainee != null)
        {
            _context.Trainees.Remove(trainee);
        }

        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private void PopulateDepartmentsDropDownList(object selectedDepartment = null)
    {
        ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name", selectedDepartment);
    }
}

WebApplication1/Controllers/crsResultsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class crsResultsController : Controller
    {
        private readonly Data.ApplicationDbContext _context;

        public crsResultsController(Data.ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: crsResults
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.crsResult.Include(c => c.Course).Include(c => c.Trainee);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: crsResults/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var crsResult = await _context.crsResult
                .Include(c => c.Course)
                .Include(c => c.Trainee)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (crsResult == null)
            {
                return NotFound();
            }

            return View(crsResult);
        }

        // GET: crsResults/Create
        public IActionResult Create()
        {
            ViewData["CourseId"] = new SelectList(_context.Courses, "Id", "Id");
            ViewData["TraineeId"] = new SelectList(_context.Trainees, "Id", "Id");
            return View();
        }

        // POST: crsResults/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Degree,CourseId,TraineeId")] crsResult crsResult)
        {
            _context.Add(crsResult);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));


        }

        // GET: crsResults/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var crsResult = await _context.crsResult.FindAsync(id);
            if (crsResult == null)
            {
                return NotFound();
            }
            ViewData["CourseId"] = new SelectList(_context.Courses, "Id", "Id", crsResult.CourseId);
            ViewData["TraineeId"] = new SelectList(_context.Trainees, "Id", "Id", crsResult.TraineeId);
            return View(crsResult);
        }

        // POST: crsResults/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Degree,CourseId,TraineeId")] crsResult crsResult)
        {
            if (id != crsResult.Id)
            {
                return NotFound();
            }


            try
            {
                _context.Update(crsResult);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!crsResultExists(crsResult.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));

        }

        // GET: crsResults/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var crsResult = await _context.crsResult
                .Include(c => c.Course)
                .Include(c => c.Trainee)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (crsResult == null)
            {
                return NotFound();
            }

            return View(crsResult);
        }

        // POST: crsResults/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var crsResult = await _context.crsResult.FindAsync(id);
            if (crsResult != null)
            {
                _context.crsResult.Remove(crsResult);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool crsResultExists(int id)
        {
            return _context.crsResult.Any(e => e.Id == id);
        }
    }
}

WebApplication1/Views/crsResults/Create.cshtml
@model WebApplication1.Models.crsResult

@{
    ViewData["Title"] = "Create";
}

<h1 class="text-center my-4">Create Course Result</h1>

<div class="card border-primary">
    <div class="card-header bg-primary text-white">
        <h4 class="mb-0">Create a new course result</h4>
    </div>
    <div class="card-body">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>
            <div class="form-group">
                <label asp-for="Degree" class="control-label"></label>
                <input asp-for="Degree" class="form-control" />
                <span asp-validation-for="Degree" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CourseId" class="control-label"></label>
                <select asp-for="CourseId" class="form-control" asp-items="ViewBag.CourseId"></select>
            </div>
            <div class="form-group">
                <label asp-for="TraineeId" class="control-label"></label>
                <select asp-for="TraineeId" class="form-control" asp-items="ViewBag.TraineeId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <div class="card-footer text-center">
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </div>
</div>

WebApplication1/Views/crsResults/Delete.cshtml
@model WebApplication1.Models.crsResult

@{
    ViewData["Title"] = "Delete";
}

<h1 class="text-center my-4 text-danger">Delete Course Result</h1>

<div class="card border-danger">
    <div class="card-header bg-danger text-white">
        <h4 class="mb-0">Are you sure you want to delete this course result?</h4>
    </div>
    <div class="card-body">
        <h4>Course Result Details</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.Degree)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Degree)
            </dd>
            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.Course)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Course.Id)
            </dd>
            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.Trainee)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Trainee.Id)
            </dd>
        </dl>
    </div>
    <div class="card-footer text-center">
        <form asp-action="Delete" class="d-inline">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="btn btn-danger" />
        </form>
        <a asp-action="Index" class="btn btn-secondary ml-2">Cancel</a>
    </div>
</div>

WebApplication1/Views/crsResults/Details.cshtml
@model WebApplication1.Models.crsResult

@{
    ViewData["Title"] = "Details";
}

<h1 class="text-center my-4">Course Result Details</h1>

<div class="card">
    <div class="card-header">
        <h4 class="mb-0">Course Result Details</h4>
    </div>
    <div class="card-body">
        <dl class="row">
            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.Trainee)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Trainee.Name)
            </dd>
            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.Degree)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Degree)
            </dd>
            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.Course)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Course.Name)
            </dd>
        </dl>
    </div>
    <div class="card-footer text-center">
        <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-primary">Edit</a>
        <a asp-action="Index" class="btn btn-secondary ml-2">Back to List</a>
    </div>
</div>

WebApplication1/Views/crsResults/Edit.cshtml
@model WebApplication1.Models.crsResult

@{
    ViewData["Title"] = "Edit";
}

<h1 class="text-center my-4">Edit Course Result</h1>

<div class="card">
    <div class="card-header">
        <h4 class="mb-0">Edit Course Result</h4>
    </div>
    <div class="card-body">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="Degree" class="control-label"></label>
                <input asp-for="Degree" class="form-control" />
                <span asp-validation-for="Degree" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CourseId" class="control-label"></label>
                <select asp-for="CourseId" class="form-control" asp-items="ViewBag.CourseId"></select>
                <span asp-validation-for="CourseId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="TraineeId" class="control-label"></label>
                <select asp-for="TraineeId" class="form-control" asp-items="ViewBag.TraineeId"></select>
                <span asp-validation-for="TraineeId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary ml-2">Back to List</a>
            </div>
        </form>
    </div>
</div>

WebApplication1/Views/crsResults/Index.cshtml
@model IEnumerable<WebApplication1.Models.crsResult>

@{
    ViewData["Title"] = "Index";
}

<!-- Dropdown Menu -->
<div class="container mt-4">
    <div class="dropdown">
        <button class="btn btn-primary btn-lg dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Menu
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="@Url.Action("Index", "Home")">Home</a>
            <a class="dropdown-item" href="@Url.Action("Index", "Courses")">Courses</a>
            <a class="dropdown-item" href="@Url.Action("Index", "Departments")">Departments</a>
            <a class="dropdown-item" href="@Url.Action("Index", "Instructors")">Instructors</a>
            <a class="dropdown-item" href="@Url.Action("Index", "Trainees")">Trainees</a>
            <a class="dropdown-item" href="@Url.Action("Index", "crsResults")">Course Result</a>
        </div>
    </div>
</div>

<h1 class="text-center my-4">Course Results</h1>

<div class="container mb-3">
    @if (!User.IsInRole("Student"))
    {
        <a asp-action="Create" class="btn btn-primary">Create New</a>
    }
</div>

<div class="card border-primary">
    <div class="card-header bg-primary text-white">
        <h4 class="mb-0">Course Results List</h4>
    </div>
    <div class="card-body">
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.First().Trainee)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.First().Degree)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.First().Course)
                    </th>
                    <th class="text-center">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Trainee.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Degree)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Course.Name)
                        </td>
                        <td class="text-center">
                            @if (User.IsInRole("Student"))
                            {
                                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info btn-sm" role="button" aria-label="View Details">Details</a>
                            }
                            else
                            {
                                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning btn-sm" role="button" aria-label="Edit Course Result">Edit</a>
                                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info btn-sm" role="button" aria-label="View Details">Details</a>
                                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm" role="button" aria-label="Delete Course Result">Delete</a>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- Bootstrap JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>