WebApplication1/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CoursesController : Controller
    {
        private readonly Data.ApplicationDbContext _context;

        public CoursesController(Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Courses.Include(c => c.Department);
            return View(await applicationDbContext.ToListAsync());
        }


        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .Include(c => c.Department)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            ViewData["departmentId"] = new SelectList(_context.Set<Department>(), "Id", "Id");
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,degree,Mindegree,departmentId")] Course course)
        {

            // Check if course name is unique
            if (_context.Courses.Any(c => c.Name == course.Name))
            {
                ModelState.AddModelError("Name", "Course name already exists.");
                return View(course);
            }

            // If unique, add the course to the database
            _context.Add(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));



        }


        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            ViewData["departmentId"] = new SelectList(_context.Set<Department>(), "Id", "Id", course.departmentId);
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,degree,Mindegree,departmentId")] Course course)
        {
            if (id != course.Id)
            {
                return NotFound();
            }


            try
            {
                _context.Update(course);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CourseExists(course.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));

        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .Include(c => c.Department)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Courses.FindAsync(id);
            if (course != null)
            {
                _context.Courses.Remove(course);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.Courses.Any(e => e.Id == id);
        }

      

    }
}

WebApplication1/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class DepartmentsController : Controller
    {
        private readonly Data.ApplicationDbContext _context;

        public DepartmentsController(Data.ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Departments
        public async Task<IActionResult> Index()
        {
            return View(await _context.Departments.ToListAsync());
        }

        // GET: Departments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Departments
                .FirstOrDefaultAsync(m => m.Id == id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        // GET: Departments/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Manager")] Department department)
        {
            // Check if the Manager field is empty
            if (string.IsNullOrWhiteSpace(department.Manager))
            {
                ModelState.AddModelError("Manager", "Manager name is required.");
                return View(department);
            }

            // Check if department name is unique
            if (_context.Departments.Any(d => d.Name == department.Name))
            {
                ModelState.AddModelError("Name", "Department name already exists.");
                return View(department);
            }

            // If all checks pass, add the department
            _context.Add(department);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }



        // GET: Departments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Departments.FindAsync(id);
            if (department == null)
            {
                return NotFound();
            }
            return View(department);
        }

        // POST: Departments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Manager")] Department department)
        {
            if (id != department.Id)
            {
                return NotFound();
            }


            try
            {
                _context.Update(department);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!DepartmentExists(department.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));


        }

        // GET: Departments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Departments
                .FirstOrDefaultAsync(m => m.Id == id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var department = await _context.Departments.FindAsync(id);
            if (department != null)
            {
                _context.Departments.Remove(department);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DepartmentExists(int id)
        {
            return _context.Departments.Any(e => e.Id == id);
        }
    }
}

WebApplication1/Controllers/StudentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers
{
    [Authorize(Roles = "Student")]
    public class StudentController : Controller
    {
        public IActionResult Dashboard()
        {
            return View();
        }
    }
}

WebApplication1/Controllers/crsResultsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class crsResultsController : Controller
    {
        private readonly Data.ApplicationDbContext _context;

        public crsResultsController(Data.ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: crsResults
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.crsResult.Include(c => c.Course).Include(c => c.Trainee);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: crsResults/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var crsResult = await _context.crsResult
                .Include(c => c.Course)
                .Include(c => c.Trainee)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (crsResult == null)
            {
                return NotFound();
            }

            return View(crsResult);
        }

        // GET: crsResults/Create
        public IActionResult Create()
        {
            ViewData["CourseId"] = new SelectList(_context.Courses, "Id", "Id");
            ViewData["TraineeId"] = new SelectList(_context.Trainees, "Id", "Id");
            return View();
        }

        // POST: crsResults/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Degree,CourseId,TraineeId")] crsResult crsResult)
        {
            _context.Add(crsResult);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));


        }

        // GET: crsResults/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var crsResult = await _context.crsResult.FindAsync(id);
            if (crsResult == null)
            {
                return NotFound();
            }
            ViewData["CourseId"] = new SelectList(_context.Courses, "Id", "Id", crsResult.CourseId);
            ViewData["TraineeId"] = new SelectList(_context.Trainees, "Id", "Id", crsResult.TraineeId);
            return View(crsResult);
        }

        // POST: crsResults/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Degree,CourseId,TraineeId")] crsResult crsResult)
        {
            if (id != crsResult.Id)
            {
                return NotFound();
            }


            try
            {
                _context.Update(crsResult);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!crsResultExists(crsResult.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));

        }

        // GET: crsResults/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var crsResult = await _context.crsResult
                .Include(c => c.Course)
                .Include(c => c.Trainee)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (crsResult == null)
            {
                return NotFound();
            }

            return View(crsResult);
        }

        // POST: crsResults/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var crsResult = await _context.crsResult.FindAsync(id);
            if (crsResult != null)
            {
                _context.crsResult.Remove(crsResult);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool crsResultExists(int id)
        {
            return _context.crsResult.Any(e => e.Id == id);
        }
    }
}

WebApplication1/Views/Student/Dashboard.cshtml
<div class="container mt-5">
    <h1 class="display-4">Student Dashboard</h1>
    <p>Welcome, @User.Identity.Name!</p>
    <p class="lead">Explore available courses and view your department information.</p>
</div>

<div class="row justify-content-center my-4">
    <div class="col-sm-6 col-md-4 mb-2">
        <a class="btn btn-primary btn-lg btn-block" href="@Url.Action("Index", "Courses")" aria-label="Navigate to Courses">
            <i class="fas fa-book"></i> View Courses
        </a>
    </div>
    <div class="col-sm-6 col-md-4 mb-2">
        <a class="btn btn-outline-primary btn-lg btn-block" href="@Url.Action("Index", "Departments")" aria-label="Navigate to Department Information">
            <i class="fas fa-building"></i> View Department
        </a>
    </div>
    <div class="col-sm-6 col-md-4 mb-2">
        <a class="btn btn-outline-success btn-lg btn-block" href="@Url.Action("Index", "crsResults")" aria-label="View Grades">
            <i class="fas fa-graduation-cap"></i> View Grades
        </a>
    </div>
    <div class="col-sm-6 col-md-4 mb-2">
        <a class="btn btn-outline-info btn-lg btn-block" href="@Url.Action("Index", "Profile")" aria-label="View Student Profile">
            <i class="fas fa-user"></i> Student Profile
        </a>
    </div>
    <div class="col-sm-6 col-md-4 mb-2">
        <a class="btn btn-outline-warning btn-lg btn-block" href="@Url.Action("Index", "Events")" aria-label="View Upcoming Events">
            <i class="fas fa-calendar-alt"></i> Upcoming Events
        </a>
    </div>
</div>

<!-- Search Bar -->
<div class="container mb-4">
    <div class="input-group">
        <input type="text" class="form-control" placeholder="Search for courses..." id="searchBar" onkeyup="filterCourses()" aria-label="Search for courses">
    </div>
</div>

<!-- Recommended Models Section -->
<div class="container mt-5">
    <h2 class="display-5">Recommended for You</h2>
    <div class="row my-4">
        <div class="col-md-6 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Recommended Courses</h5>
                    <ul id="coursesList">
                        <li><a href="@Url.Action("Details", "Courses", new { id = 1 })">Introduction to Web Development</a></li>
                        <li><a href="@Url.Action("Details", "Courses", new { id = 2 })">Advanced Database Management</a></li>
                        <li><a href="@Url.Action("Details", "Courses", new { id = 3 })">Machine Learning Fundamentals</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-6 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Upcoming Assignments</h5>
                    <ul>
                        <li>Project: Web App UI - Due in 3 days</li>
                        <li>Essay: Introduction to AI - Due in 5 days</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="row my-4">
        <div class="col-md-6 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Department News</h5>
                    <p>Don't miss the upcoming seminar on "Sustainable Engineering" next week!</p>
                </div>
            </div>
        </div>
        <div class="col-md-6 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Scholarship Opportunities</h5>
                    <p>Apply for the "Student Excellence Scholarship" by the end of this month.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function filterCourses() {
        let input = document.getElementById('searchBar').value.toLowerCase();
        let courses = document.querySelectorAll('#coursesList li');
        courses.forEach(course => {
            let courseName = course.innerText.toLowerCase();
            if (courseName.includes(input)) {
                course.style.display = '';
            } else {
                course.style.display = 'none';
            }
        });
    }
</script>