WebApplication1/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CoursesController : Controller
    {
        private readonly Data.ApplicationDbContext _context;

        public CoursesController(Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Courses.Include(c => c.Department);
            return View(await applicationDbContext.ToListAsync());
        }


        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .Include(c => c.Department)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            ViewData["departmentId"] = new SelectList(_context.Set<Department>(), "Id", "Id");
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,degree,Mindegree,departmentId")] Course course)
        {

            // Check if course name is unique
            if (_context.Courses.Any(c => c.Name == course.Name))
            {
                ModelState.AddModelError("Name", "Course name already exists.");
                return View(course);
            }

            // If unique, add the course to the database
            _context.Add(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));



        }


        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            ViewData["departmentId"] = new SelectList(_context.Set<Department>(), "Id", "Id", course.departmentId);
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,degree,Mindegree,departmentId")] Course course)
        {
            if (id != course.Id)
            {
                return NotFound();
            }


            try
            {
                _context.Update(course);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CourseExists(course.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));

        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .Include(c => c.Department)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Courses.FindAsync(id);
            if (course != null)
            {
                _context.Courses.Remove(course);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.Courses.Any(e => e.Id == id);
        }

      

    }
}

WebApplication1/Controllers/InstructorsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class InstructorsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public InstructorsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Instructors
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Instructors
                .Include(i => i.Course)
                .Include(i => i.Department);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Instructors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var instructor = await _context.Instructors
                .Include(i => i.Course)
                .Include(i => i.Department)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (instructor == null)
            {
                return NotFound();
            }

            return View(instructor);
        }

        // GET: Instructors/Create
        public IActionResult Create()
        {
            ViewData["CourseId"] = new SelectList(_context.Courses, "Id", "Name");
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Image,Salary,Address,CourseId,DepartmentId")] Instructor instructor)
        {
            // Manual validation
            var errors = new List<string>();

            if (string.IsNullOrEmpty(instructor.Name))
            {
                errors.Add("Name is required.");
            }
            if (string.IsNullOrEmpty(instructor.Image))
            {
                errors.Add("Image URL is required.");
            }
            if (instructor.Salary <= 0)
            {
                errors.Add("Salary must be greater than zero.");
            }
            if (string.IsNullOrEmpty(instructor.Address))
            {
                errors.Add("Address is required.");
            }
            if (instructor.CourseId <= 0)
            {
                errors.Add("A valid course must be selected.");
            }
            if (instructor.DepartmentId <= 0)
            {
                errors.Add("A valid department must be selected.");
            }

            if (errors.Any())
            {
                // Re-populate dropdown lists
                ViewData["CourseId"] = new SelectList(_context.Courses, "Id", "Name", instructor.CourseId);
                ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name", instructor.DepartmentId);

                // Add errors to ViewData to display in the view
                ViewData["Errors"] = errors;
                return View(instructor);
            }

            try
            {
                _context.Add(instructor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException)
            {
                // Log the exception and show a generic error message
                ViewData["Errors"] = new List<string> { "Unable to save changes. Please try again." };
                ViewData["CourseId"] = new SelectList(_context.Courses, "Id", "Name", instructor.CourseId);
                ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name", instructor.DepartmentId);
                return View(instructor);
            }
        }



        // GET: Instructors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var instructor = await _context.Instructors.FindAsync(id);
            if (instructor == null)
            {
                return NotFound();
            }

            ViewData["CourseId"] = new SelectList(_context.Courses, "Id", "Name", instructor.CourseId);
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name", instructor.DepartmentId);
            return View(instructor);
        }

        // POST: Instructors/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Image,Salary,Address,CourseId,DepartmentId")] Instructor instructor)
        {
            if (id != instructor.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(instructor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InstructorExists(instructor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["CourseId"] = new SelectList(_context.Courses, "Id", "Name", instructor.CourseId);
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name", instructor.DepartmentId);
            return View(instructor);
        }

        // GET: Instructors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var instructor = await _context.Instructors
                .Include(i => i.Course)
                .Include(i => i.Department)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (instructor == null)
            {
                return NotFound();
            }

            return View(instructor);
        }

        // POST: Instructors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var instructor = await _context.Instructors.FindAsync(id);
            if (instructor != null)
            {
                _context.Instructors.Remove(instructor);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        private bool InstructorExists(int id)
        {
            return _context.Instructors.Any(e => e.Id == id);
        }
    }
}

WebApplication1/Controllers/TraineesController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using static System.Runtime.InteropServices.JavaScript.JSType;
using WebApplication1.Models;

public class TraineesController : Controller
{
    private readonly WebApplication1.Data.ApplicationDbContext _context;

    public TraineesController(WebApplication1.Data.ApplicationDbContext context)
    {
        _context = context;
    }
    private bool TraineeExists(int id)
    {
        return _context.Trainees.Any(e => e.Id == id);
    }

    // GET: Trainees
    public async Task<IActionResult> Index()
    {
        var applicationDbContext = _context.Trainees.Include(t => t.Department);
        return View(await applicationDbContext.ToListAsync());
    }

    // GET: Trainees/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var trainee = await _context.Trainees
            .Include(t => t.Department)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (trainee == null)
        {
            return NotFound();
        }

        return View(trainee);
    }

    // GET: Trainees/Create
    public IActionResult Create()
    {
        PopulateDepartmentsDropDownList();
        return View();
    }

    // POST: Trainees/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Name,Image,Address,Grade,DepartmentId")] Trainee trainee)
    {
        // Manual validation
        var errors = new List<string>();

        if (string.IsNullOrEmpty(trainee.Name))
        {
            errors.Add("Name is required.");
        }
        if (string.IsNullOrEmpty(trainee.Image))
        {
            errors.Add("Image URL or path is required.");
        }
        if (string.IsNullOrEmpty(trainee.Address))
        {
            errors.Add("Address is required.");
        }
        if (trainee.Grade <= 0)
        {
            errors.Add("Grade must be greater than zero.");
        }
        if (trainee.DepartmentId <= 0)
        {
            errors.Add("A valid department must be selected.");
        }

        if (errors.Any())
        {
            PopulateDepartmentsDropDownList(trainee.DepartmentId);
            ViewData["Errors"] = errors;
            return View(trainee);
        }

        try
        {
            _context.Add(trainee);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        catch (DbUpdateException ex)
        {
            ViewData["Errors"] = new List<string> { "Unable to save changes. Please try again." };
            PopulateDepartmentsDropDownList(trainee.DepartmentId);
            return View(trainee);
        }
    }
    // GET: Trainees/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var trainee = await _context.Trainees.FindAsync(id);
        if (trainee == null)
        {
            return NotFound();
        }

        // Populate drop-down lists
        ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name", trainee.DepartmentId);

        return View(trainee);
    }


    // POST: Trainees/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Image,Address,Grade,DepartmentId")] Trainee trainee)
    {
        if (id != trainee.Id)
        {
            return NotFound();
        }

        // Ensure the departmentId is valid
        var departmentExists = await _context.Departments.AnyAsync(d => d.Id == trainee.DepartmentId);
        if (!departmentExists)
        {
            ModelState.AddModelError("DepartmentId", "Selected department does not exist.");
        }

        if (ModelState.IsValid)
        {
            try
            {
                var existingTrainee = await _context.Trainees.FindAsync(id);
                if (existingTrainee == null)
                {
                    return NotFound();
                }

                _context.Entry(existingTrainee).CurrentValues.SetValues(trainee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TraineeExists(trainee.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
        }

        // Repopulate the drop-down list in case of validation failure
        ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name", trainee.DepartmentId);
        return View(trainee);
    }


    // GET: Trainees/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var trainee = await _context.Trainees
            .Include(t => t.Department)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (trainee == null)
        {
            return NotFound();
        }

        return View(trainee);
    }

    // POST: Trainees/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var trainee = await _context.Trainees.FindAsync(id);
        if (trainee != null)
        {
            _context.Trainees.Remove(trainee);
        }

        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private void PopulateDepartmentsDropDownList(object selectedDepartment = null)
    {
        ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name", selectedDepartment);
    }
}

WebApplication1/Views/Instructors/Create.cshtml
@model WebApplication1.Models.Instructor

@{
    ViewData["Title"] = "Create Instructor";
    var errors = ViewData["Errors"] as List<string>;
}

<div class="container">
    <h1 class="text-center my-4">Create Instructor</h1>

    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h4 class="mb-0">New Instructor</h4>
                </div>
                <div class="card-body">
                    <form asp-action="Create">
                        @if (errors != null && errors.Any())
                        {
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach (var error in errors)
                                    {
                                        <li>@error</li>
                                    }
                                </ul>
                            </div>
                        }

                        <div class="form-group">
                            <label asp-for="Name" class="control-label"></label>
                            <input asp-for="Name" class="form-control" placeholder="Enter name" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Image" class="control-label"></label>
                            <input asp-for="Image" class="form-control" placeholder="Enter image URL" />
                            <span asp-validation-for="Image" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Salary" class="control-label"></label>
                            <input asp-for="Salary" type="number" step="0.01" class="form-control" placeholder="Enter salary" />
                            <span asp-validation-for="Salary" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Address" class="control-label"></label>
                            <input asp-for="Address" class="form-control" placeholder="Enter address" />
                            <span asp-validation-for="Address" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="CourseId" class="control-label"></label>
                            <select asp-for="CourseId" class="form-control" asp-items="ViewBag.CourseId">
                                <option value="">Select Course</option>
                            </select>
                            <span asp-validation-for="CourseId" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="DepartmentId" class="control-label"></label>
                            <select asp-for="DepartmentId" class="form-control" asp-items="ViewBag.DepartmentId">
                                <option value="">Select Department</option>
                            </select>
                            <span asp-validation-for="DepartmentId" class="text-danger"></span>
                        </div>

                        <div class="form-group text-center">
                            <input type="submit" value="Create" class="btn btn-primary" />
                            <a asp-action="Index" class="btn btn-secondary ml-2">Back to List</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

WebApplication1/Views/Instructors/Delete.cshtml
@model WebApplication1.Models.Instructor

@{
    ViewData["Title"] = "Delete";
}

<div class="container mt-5">
    <h1 class="text-center text-danger">Delete Instructor</h1>

    <h3 class="text-center">Are you sure you want to delete this?</h3>

    <div class="card mt-4">
        <div class="card-body">
            <h4 class="card-title text-center">Instructor Details</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-4 text-right">
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt class="col-sm-4 text-right">
                    @Html.DisplayNameFor(model => model.Image)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.Image)
                </dd>
                <dt class="col-sm-4 text-right">
                    @Html.DisplayNameFor(model => model.Salary)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.Salary)
                </dd>
                <dt class="col-sm-4 text-right">
                    @Html.DisplayNameFor(model => model.Address)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.Address)
                </dd>
                <dt class="col-sm-4 text-right">
                    @Html.DisplayNameFor(model => model.Course)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.Course.Id)
                </dd>
                <dt class="col-sm-4 text-right">
                    @Html.DisplayNameFor(model => model.Department)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.Department.Id)
                </dd>
            </dl>

            <div class="text-center mt-4">
                <form asp-action="Delete" class="d-inline">
                    <input type="hidden" asp-for="Id" />
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </form>
                <a asp-action="Index" class="btn btn-secondary ml-2">Back to List</a>
            </div>
        </div>
    </div>
</div>

WebApplication1/Views/Instructors/Details.cshtml
@model WebApplication1.Models.Instructor

@{
    ViewData["Title"] = "Details";
}

<h1 class="text-center">@Model.Name's Details</h1>

<div class="card mb-3">
    <div class="row g-0">
        <div class="col-md-4">
            <!-- Display the image -->
            <img src="~/@Model.Image" class="img-fluid rounded-start" alt="Instructor Image" style="max-width: 100%; height: auto;" />
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h4 class="card-title">@Model.Name</h4>
                <dl class="row">
                    <dt class="col-sm-4">@Html.DisplayNameFor(model => model.Salary)</dt>
                    <dd class="col-sm-8">@Html.DisplayFor(model => model.Salary) EGP</dd>

                    <dt class="col-sm-4">@Html.DisplayNameFor(model => model.Address)</dt>
                    <dd class="col-sm-8">@Html.DisplayFor(model => model.Address)</dd>

                    <dt class="col-sm-4">@Html.DisplayNameFor(model => model.Course)</dt>
                    <dd class="col-sm-8">@Html.DisplayFor(model => model.Course.Name)</dd>

                    <dt class="col-sm-4">@Html.DisplayNameFor(model => model.Department)</dt>
                    <dd class="col-sm-8">@Html.DisplayFor(model => model.Department.Name)</dd>
                </dl>
            </div>
        </div>
    </div>
</div>

<div class="text-center">
    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model?.Id">Edit</a>
    <a class="btn btn-secondary" asp-action="Index">Back to List</a>
</div>

WebApplication1/Views/Instructors/Edit.cshtml
@model WebApplication1.Models.Instructor

@{
    ViewData["Title"] = "Edit";
}

<h1 class="text-center">Edit Instructor</h1>

<h4 class="text-center">Instructor</h4>
<hr />
<div class="d-flex justify-content-center">
    <div class="col-md-6">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CourseId" class="control-label"></label>
                <select asp-for="CourseId" class="form-control" asp-items="ViewBag.CourseId"></select>
                <span asp-validation-for="CourseId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentId" class="control-label"></label>
                <select asp-for="DepartmentId" class="form-control" asp-items="ViewBag.departmentId"></select>
                <span asp-validation-for="DepartmentId" class="text-danger"></span>
            </div>
            <div class="form-group text-center">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="text-center mt-3">
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

WebApplication1/Views/Instructors/Index.cshtml
@model IEnumerable<WebApplication1.Models.Instructor>

@{
    ViewData["Title"] = "Index";
}

<!-- Dropdown Menu -->
<div class="container mt-4">
    <div class="dropdown">
        <button class="btn btn-primary btn-lg dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Menu
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="@Url.Action("Index", "Home")">Home</a>
            <a class="dropdown-item" href="@Url.Action("Index", "Courses")">Courses</a>
            <a class="dropdown-item" href="@Url.Action("Index", "Departments")">Departments</a>
            <a class="dropdown-item" href="@Url.Action("Index", "Instructors")">Instructors</a>
            <a class="dropdown-item" href="@Url.Action("Index", "Trainees")">Trainees</a>
            <a class="dropdown-item" href="@Url.Action("Index", "crsResults")">Course Result</a>
        </div>
    </div>
</div>

<!-- Title and Button -->
<div class="container text-center mb-4">
    <h1 class="display-4">Instructors List</h1>
    <p>
        <a class="btn btn-success btn-lg" asp-action="Create">Create New</a>
    </p>
</div>

<!-- Instructors Table -->
<div class="container">
    <table class="table table-striped table-hover">
        <thead class="thead-dark">
            <tr>
                <th>Name</th>
                <th>Image</th>
                <th>Salary</th>
                <th>Address</th>
                <th>Course</th>
                <th>Department</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Name)</td>
                    <td>
                        @if (!string.IsNullOrEmpty(item.Image))
                        {
                            <img src="~/@item.Image" alt="Instructor Image" class="img-thumbnail" style="max-width: 100px; height: auto;" />
                        }
                        else
                        {
                            <span>No Image</span>
                        }
                    </td>
                    <td>@Html.DisplayFor(modelItem => item.Salary) $</td>
                    <td>@Html.DisplayFor(modelItem => item.Address)</td>
                    <td>@Html.DisplayFor(modelItem => item.Course.Name)</td>
                    <td>@Html.DisplayFor(modelItem => item.Department.Name)</td>
                    <td>
                        <a class="btn btn-info btn-sm mx-1" asp-action="Edit" asp-route-id="@item.Id" role="button" aria-label="Edit Instructor">Edit</a>
                        <a class="btn btn-primary btn-sm mx-1" asp-action="Details" asp-route-id="@item.Id" role="button" aria-label="View Details">Details</a>
                        <a class="btn btn-danger btn-sm mx-1" asp-action="Delete" asp-route-id="@item.Id" role="button" aria-label="Delete Instructor">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- Bootstrap JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>